# Generated by Django 4.2.8 on 2024-03-27 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField(default=datetime.date.today, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
