# Generated by Django 4.2.8 on 2024-03-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='searchable_text',
        ),
    ]
