# Generated by Django 4.2.8 on 2024-03-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_searchable_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=None),
        ),
    ]
